### ISSUE TITLE
Enable Dark Mode Option Does Nothing

### ISSUE THREAD

**Issue by colinalvin63** [Garoe/ThunderKeepPlus#10]
Hi Garoe,
I'm always using ThunderKeep to give me access to Google Keep within Thunderbird - very useful.

Google has recently provided a way to invert the colour scheme of Keep to a Dark Mode. Unfortunately, when I try enabling the Dark Mode within Settings, it doesn't seem to do anything - the background remains white and the text black. It would be great if it was the other way around.
I'm not sure whether this is a Google issue, a Thunderbird issue or a ThunderKeep issue.
It would be great if you could test the issue to find out.
Regards, Colin

**Comment by Gara-Dorta** [comment]
Hi Colin,

I'm afraid this issue is most likely a Thunderbird issue, as the plugin is doing a little more than just opening a default Thunderbird browser window pointing to the google keep site. Oddly enough, the dark mode works on my machine. What version of thunderbird and ThunderkeepPlus are you using? Also, on what operating system?
