### ISSUE TITLE
Change the NAME

### ISSUE THREAD

**Issue by CharlieDav1d** [Garoe/ThunderKeepPlus#16]
this is listed as KeepPlus. IT IS NOT KeepPass or similar. It IS GOOGLE
Change the bloody name, as it has nothing to do with KeePass.
Try ThunderGooglePass

**Comment by Gara-Dorta** [comment]
Thanks for the suggestion. I'm not sure what you mean by it being listed as KeepPlus. Can you clarify this? To give a bit of context, the name is a combination of **Thunder**bird, Google **Keep** and **Plus** , the main historical reason for this is that this addon is a fork of ThunderKeep. So the plus was added to denote that it was better than the former, as ThunderKeep was abandoned. Since this is not an official google product I prefer to be very cautious with using the google trademark. In other words, I do not want to be demanded by google for using their company name without permission. Thus, I do not intend to change the name and I'll close this issue. In any case, if this is something you feel strongly about, you are more than welcome to fork the project, rename it and publish it with a new name.

**Comment by Gara-Dorta** [comment]
After thinking a bit more about it and seeing that other unofficial google related addons have had not problems. I've decided to update the name as suggested. The new version has already been released under "Google Keep Tab"
